#
# Copyright 2017 IntraFind Software AG. All rights reserved.
#

security:
  user:
    name: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=
    password: jOLtvCtDi1YxR/IW4XPI6hjvi2LNOYgMEY6YSz9HWJs=

server:
  port: 8001
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: changeit
#    key-password: changeit
#    key-alias: alias

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: sitesearch

