#
# Copyright 2017 IntraFind Software AG. All rights reserved.
#

#server.error.whitelabel.enabled=false # to fix Swagger issue

logging:
  level:
    org.springframework.web: INFO
    com.intrafind: INFO

security:
  user:
    name: ${security.user.password}
    password: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=

sitesearch:
  queryCountEnabled: true

server:
  port: 8001
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: ${security.user.password}
#    key-password: ${security.user.password}
#    key-alias: alias

spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest

#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: sitesearch

