#
# Copyright 2017 IntraFind Software AG. All rights reserved.
#

#server.error.whitelabel.enabled=false # to fix Swagger issue

#facebook:
#  client:
#    clientId: 277335132728142
#    clientSecret: 1f10244d39f6231e15a1fef8148b02cf
#
#github:
#  client:
#    clientId: 51ddf3aea6097a04b03c
#    clientSecret: 23a073815a370e20fb6f1d786fc68ad9948d6af4

logging:
  level:
    org.springframework.web: INFO
    com.intrafind: INFO

security:
  user:
    name: ${security.user.password}
    password: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=
  oauth2:
    client:
      clientId: 61cf2f1798f16758a998
      clientSecret: 65e0b85ddeda3b6499161f1cd78a5a6d7bf9cd55
#    clientSecret: ${random.uuid} # add valid token to your local configuration
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      pre-established-redirect-uri: https://api.sitesearch.cloud/admin.html
      registered-redirect-uri: https://api.sitesearch.cloud/admin.html
      use-current-uri: true
    resource:
      userInfoUri: https://api.github.com/user

#github:
#  client:
#    clientId: 51ddf3aea6097a04b03c
#    clientSecret: 23a073815a370e20fb6f1d786fc68ad9948d6af4
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userAuthorizationUri: https://github.com/login/oauth/authorize
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://api.github.com/user

sitesearch:
  queryCountEnabled: true

server:
  port: 8001

spring:
  kafka:
    consumer:
      group-id: foo
      auto-offset-reset: earliest

#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: sitesearch

