version: "2.0"
services:

  sitesearch-search-service:
    image: docker-registry.sitesearch.cloud/intrafind/sis-search-service:2.4.6.4-dev-1
    container_name: sitesearch-search-service
    restart: always
    depends_on:
      - sitesearch-elasticsearch
      - sitesearch-elasticsearch-1
      - sitesearch-elasticsearch-quorum
    environment:
      - elasticsearch_hosts=sitesearch-elasticsearch, sitesearch-elasticsearch-1, sitesearch-elasticsearch-quorum
    volumes:
      - /srv/sitesearch-search-service:/srv/sitesearch-search-service:rw
    networks:
      - sitesearch

  sitesearch-search-service-1:
    image: docker-registry.sitesearch.cloud/intrafind/sis-search-service:2.4.6.4-dev-1
    container_name: sitesearch-search-service-1
    restart: always
    depends_on:
      - sitesearch-elasticsearch
      - sitesearch-elasticsearch-1
      - sitesearch-elasticsearch-quorum
    environment:
      - elasticsearch_hosts=sitesearch-elasticsearch, sitesearch-elasticsearch-1, sitesearch-elasticsearch-quorum
    volumes:
      - /srv/sitesearch-search-service-1:/srv/sitesearch-search-service:rw
    networks:
      - sitesearch

  sitesearch-elasticsearch:
    image: docker-registry.sitesearch.cloud/intrafind/sis-elasticsearch:2.4.6.7
    container_name: sitesearch-elasticsearch
    restart: always
    environment:
      - unicast_hosts=sitesearch-elasticsearch:9300, sitesearch-elasticsearch-1:9300, sitesearch-elasticsearch-quorum:9300
      - minimum_master_nodes=2
    volumes:
      - /srv/sitesearch-elasticsearch/data:/home/app_user/data:rw
    networks:
      - sitesearch

  sitesearch-elasticsearch-1:
    image: docker-registry.sitesearch.cloud/intrafind/sis-elasticsearch:2.4.6.7
    container_name: sitesearch-elasticsearch-1
    restart: always
    environment:
      - unicast_hosts=sitesearch-elasticsearch:9300, sitesearch-elasticsearch-1:9300, sitesearch-elasticsearch-quorum:9300
      - minimum_master_nodes=2
    volumes:
      - /srv/sitesearch-elasticsearch-1/data:/home/app_user/data:rw
    networks:
      - sitesearch

  sitesearch-elasticsearch-quorum:
    image: docker-registry.sitesearch.cloud/intrafind/sis-elasticsearch:2.4.6.7
    container_name: sitesearch-elasticsearch-quorum
    restart: always
    environment:
      - unicast_hosts=sitesearch-elasticsearch:9300, sitesearch-elasticsearch-1:9300, sitesearch-elasticsearch-quorum:9300
      - minimum_master_nodes=2
      - ELASTICSEARCH_NODE_DATA=false
    volumes:
      - /srv/sitesearch-elasticsearch-quorum/data:/home/app_user/data:rw
    networks:
      - sitesearch

networks:
  sitesearch:
    external:
      name: sitesearch
